import logo from "./images/logo.svg"
import iconCart from "./images/icon-cart.svg"
import iconNext from "./images/icon-next.svg"
import iconPlus from "./images/icon-plus.svg"
import iconPrevious from "./images/icon-previous.svg"
import iconMinus from "./images/icon-minus.svg"
import iconMenu from "./images/icon-menu.svg"
import iconDelet from "./images/icon-delete.svg"
import iconClose from "./images/icon-close.svg"
import iconCloseGray from "./images/icon-close-gray.svg"
import iconCloseOrange from "./images/icon-close-orange.svg"
import iconCartWhite from "./images/icon-cart-white.svg"
import iconCartBlack from "./images/icon-cart-black.svg"
import imageAvatar from "./images/image-avatar.png"
import imageProduct1 from "./images/image-product-1.jpg"
import imageProduct2 from "./images/image-product-2.jpg"
import imageProduct3 from "./images/image-product-3.jpg"
import imageProduct4 from "./images/image-product-4.jpg"
import imageProductThumbnail1 from "./images/image-product-1-thumbnail.jpg"
import imageProductThumbnail2 from "./images/image-product-2-thumbnail.jpg"
import imageProductThumbnail3 from "./images/image-product-3-thumbnail.jpg"
import imageProductThumbnail4 from "./images/image-product-4-thumbnail.jpg"


export {logo,iconCart,iconNext,iconPlus,iconPrevious,iconCloseGray,iconMinus,iconCloseOrange,iconMenu,iconDelet,iconClose,imageAvatar,iconCartWhite,iconCartBlack,imageProduct1,imageProduct2,imageProduct3,imageProduct4,imageProductThumbnail1,imageProductThumbnail2,imageProductThumbnail3,imageProductThumbnail4}