import logo from "./assets/logo.svg"
import iconCart from "./assets/icon-cart.svg"
import iconNext from "./assets/icon-next.svg"
import iconPlus from "./assets/icon-plus.svg"
import iconPrevious from "./assets/icon-previous.svg"
import iconMinus from "./assets/icon-minus.svg"
import iconMenu from "./assets/icon-menu.svg"
import iconDelet from "./assets/icon-delete.svg"
import iconClose from "./assets/icon-close.svg"
import iconCloseGray from "./assets/icon-close-gray.svg"
import iconCloseOrange from "./assets/icon-close-orange.svg"
import iconCartWhite from "./assets/icon-cart-white.svg"
import iconCartBlack from "./assets/icon-cart-black.svg"
import imageAvatar from "./assets/image-avatar.png"
import imageProduct1 from "./assets/image-product-1.jpg"
import imageProduct2 from "./assets/image-product-2.jpg"
import imageProduct3 from "./assets/image-product-3.jpg"
import imageProduct4 from "./assets/image-product-4.jpg"
import imageProductThumbnail1 from "./assets/image-product-1-thumbnail.jpg"
import imageProductThumbnail2 from "./assets/image-product-2-thumbnail.jpg"
import imageProductThumbnail3 from "./assets/image-product-3-thumbnail.jpg"
import imageProductThumbnail4 from "./assets/image-product-4-thumbnail.jpg"


export {logo,iconCart,iconNext,iconPlus,iconPrevious,iconCloseGray,iconMinus,iconCloseOrange,iconMenu,iconDelet,iconClose,imageAvatar,iconCartWhite,iconCartBlack,imageProduct1,imageProduct2,imageProduct3,imageProduct4,imageProductThumbnail1,imageProductThumbnail2,imageProductThumbnail3,imageProductThumbnail4}